### ISSUE TITLE
Linux install of /etc/udev/rules.d/52-airspyhf.rules maybe could add group and mode

### ISSUE THREAD

**Issue by mahtin** [airspy/airspyhf#46]
In order to remove the need to run everything accessing the AirspyHF+ via `sudo`; I'm wondering if the following is acceptable as a change to the s/w? (If so, I'll PR it). It does work.

The distributed `52-airspyhf.rules` file does not specify the group id or mode for the created device file `/dev/airspyhf-*`. I've added `GROUP="dialout", MODE="0660",` to the file and now I can use the AirspyHF+ without `sudo`. My file is as follows:

```
$ cat /etc/udev/rules.d/52-airspyhf.rules 
ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", SYMLINK+="airspyhf-%k", GROUP="dialout", MODE="0660", TAG+="uaccess"
$
```
I picked `dialout` as the group as I was already a member. I don't know if there's a better choice (maybe `gpio` or `netdev`? - neither is great!)

Thoughts. As I said, I'm happy to PR this.

**Comment by jketterl** [comment]
I'll just chime in here since I just noticed that the udev rules have been reduced to `uaccess` tagging in this repository. I don't know where this movement started, I think I do understand the idea behind it, but I can tell that it is insufficient to cover all use cases.

From what I can tell, the idea is that the uaccess tag will handle the permissions of the devices "automagically" through ACLs when a user logs in. From what I can tell, this is probably working for SDR applications running in userspace. The problem with the uaccess tagging is that it leaves a big hole for anything that does not run in a systemd user session, for example any application running as a systemd service unit will not be able to access the devices (unless it is run as root, which is probably not a good choice in general).

I have brought this to the attention of the Debian maintainers of the libairspy packages (yes, i know that's a different library, but they introduced the same change a while back and it cause the same issues) and they have now brought back the group assignment for "plugdev" in the most recent version.

See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033121

I don't know if there's another solution to this in the systemd universe. If you know how to solve this differently, please let me know. For me, it seems there has to be at least some "classical" permissions in place for this to work correctly, so I'd recommend combining the best of both worlds, that is: having both a group assignment and uaccess tagging.

**Comment by mahtin** [comment]
The key takeaway from that reference is:
```
 * use group plugdev along with uaccess to allow for systemd services
```
Which makes sense.

Plus, `plugdev` is a better choice and works well for me.
```
$ grep plugdev /etc/group
plugdev:x:46:martin
$
$ cat /etc/udev/rules.d/52-airspyhf.rules 
ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", SYMLINK+="airspyhf-%k", GROUP="plugdev", MODE="0660", TAG+="uaccess"
$
```

With 0660 mode and group "plugdev" this will be a step forward. Those still running as root (ie. Everyone following the instructions) won't be affected. Those following newer versions of instructions will benefit. (Or their system will benefit - more correctly).

I'll PR it and see how this goes.

**Comment by mahtin** [comment]
Ok. There's history here. @aeroevan needs to chime in because of this edit. https://github.com/airspy/airspyhf/commit/6d4469d80d4788bae24b8d5cb8558770f868ae2d

A year ago the group and mode was removed and replaced uaccess. Why not both as I'd like to recommend?

**Comment by AsciiWolf** [comment]
It would be ideal if the udev rules (for both airspy and airspyhf) were submitted into upstream udevd (systemd), just like other devices do. It would prevent similar issues and make airspy work out-of-box on all modern Linux distributions (including containerized environments like Flatpak, Snap or AppImage).

**Comment by mahtin** [comment]
Yes that would be idea (and I believe needs a different issue opened - along with an advocate to do that work); however, that doesn't detract from this issue and its (present day) need.

**Comment by aeroevan** [comment]
On fedora there isn't a plugdev group, and removing that reference was needed to get running on my fedora-iot hosts. There probably is a better way to handle cross-distro support though, I'm not really an expert in udev rules and would be willing to test on a fedora install. I probably should have tested on the debian side too, but I don't currently run any debian based systems

**Comment by jj1bdx** [comment]
The same modification was needed to run libairspyhf on Raspberry Pi OS 64bit. See this comment: https://github.com/jj1bdx/airspy-fmradion/issues/77#issuecomment-2011091931

**Comment by jj1bdx** [comment]
The same modification was also needed to run libairspyhf on Ubuntu 22.04.4 LTS.

**Comment by bigalnz** [comment]
+1 on this issue - I just spent an hour trying to workout why airspyhf_info will only run as sudo. Still a little unclear on steps from here?
Add my user to plugdev and modify the udev rule?

**Comment by vielmetti** [comment]
I happened upon this issue when getting OpenWebRX+ to run on my AirSPY HF+. As distributed, the v1.2.61 version udev rules generate this exception:

```
owrx.source.airspy - ERROR - Exception during postStart()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/owrx/source/__init__.py", line 427, in start
    self.postStart()
  File "/usr/lib/python3/dist-packages/owrx/source/connector.py", line 62, in postStart
self.controlSocket.connect(("localhost", self.controlPort))
ConnectionRefusedError: [Errno 111] Connection refused
```


see also discussion at https://groups.io/g/openwebrx/topic/103545886

**Comment by touil** [comment]
Unrelated to this repos.

**Comment by darksidelemm** [comment]
I'm going to chime in on this issue - from a fresh Raspbian Bookworm Lite install, the same modifications to the supplied .rules file were needed to be able to access an Airspy HF unit without root.

I ended up changing the rules to:
```
ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", SYMLINK+="airspyhf-%k", MODE="660", GROUP="plugdev"
```

It sure would be nice if this repository shipped with a .rules file that worked on Debian/Raspbian... or at least mentioned the issue in the Readme. I'm sure this is affecting a lot of users.

**Comment by touil** [comment]
How many other users will be unhappy to see the lib breaking for their distro?

**Comment by darksidelemm** [comment]
Then maybe you should mention in your readme that this is an known issue and at least point to a solution?

**Comment by touil** [comment]
Feel free to propose something.

**Comment by markjfine** [comment]
@darksidelemm 
Is there a build variable that .rules could determine it's a Raspian build. If so, then maybe .rules could be altered with a conditional. Something like:
```
ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", SYMLINK+="airspyhf-%k", TAG+="uaccess"
ENV{Build_Type}=="Debian/Raspbian", ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", MODE="660", GROUP="plugdev"
```
Since this is a pretty niche thing, perhaps someone could find out what the proper conditional would replace `ENV{Build_Type}=="Debian/Raspbian"` and test it. @touil might be able to then implement it so it doesn't negatively impact other Linux, Windows, or macOS builds.

@touil 
Would this be helpful?

**Comment by touil** [comment]
Who will test every single distro for regressions?

**Comment by markjfine** [comment]
> Who will test every single distro for regressions? 

Good point.

**Comment by darksidelemm** [comment]
I'm sure @aeroevan would happily test on Fedora, since they made the change which made the udev rule work on Fedora (but broke it on Debian-based distros because 
> I probably should have tested on the debian side too, but I don't currently run any debian based systems

https://github.com/airspy/airspyhf/issues/46#issuecomment-1905229881

I note that that the [udev rule for the Airspy R2](https://github.com/airspy/airspyone_host/blob/master/airspy-tools/52-airspy.rules ) over in the airspyone_host repository is currently:
```
ATTR{idVendor}=="1d50", ATTR{idProduct}=="60a1", SYMLINK+="airspy-%k", MODE="660", GROUP="plugdev"
```
which is the same as what was in this repo for the airspy HF until the change by @aeroevan https://github.com/airspy/airspyhf/commit/6d4469d80d4788bae24b8d5cb8558770f868ae2d

**Comment by bigalnz** [comment]
I have found that my python code which uses a ctypes wrapper for the airspy
lib suddenly started reporting dropped samples on raspbian. Would this be
related to this thread?

Al

"Beat it punk!"
- Clint Eastwood

**Comment by darksidelemm** [comment]
If the software is able to open the airspy and get any samples at all, then very likely it's a different issue. 
This issue is about incorrect udev rules not permitting non-root users from open the airspy (in this case an airspyHF) at all.

**Comment by darksidelemm** [comment]
I spent a bit of time this morning trying out the official spyserver setup instructions from https://airspy.com/quickstart/ to see how a new user would experience this problem.
Most of the instructions there point to the airspyone_host repo, but just below that is a link to the automated install script  https://airspy.com/downloads/install-spyserver-rpi.sh "which will do everything for you with a single command". 

Right now (I just tested this with a fresh install of Raspbian Bookworm), and I'm guessing since October 2022, this setup script does not result in a working spyserver for the Airspy HF, because of the changes made to the udev rule. The setup script installs the airspyhf drivers from this repository, using its udev rule.

Users will run the script, start up the spyserver@hf service as per the presented instructions, and will find that the server isn't responding to connections. If they go digging into journalctl, they might find the key "Could not acquire the device" message, which with some searching might lead them to this issue, or perhaps ask on the airspy mailing list for help as to why it's not working.

Surely it would be better if the airspy-recommended script actually worked out of the box?

**Comment by aeroevan** [comment]
Adding groups that don't exist on other distributions won't work, which is why modern distros just use the uaccess tag: https://wiki.debian.org/USB/GadgetSetup 

For me I'm running SDRs in podman quadlets in various headless fedora-iot systems where there is no plugdev group, where exactly is the uaccess tag not being applied?

**Comment by darksidelemm** [comment]
The example use-case where the current udev rule is causing issues is that of a spyserver, running as a systemd service, setup using the airspy-recommended installation script: https://airspy.com/downloads/install-spyserver-rpi.sh

This script is the recommended setup approach for a spyserver on a Raspberry Pi. Right now it doesn't work with the Airspy HF due to the udev rule, with neither the systemd service, or running spyserver from a ssh session being able to access the Airspy HF.

So... how can this be made to work? Is there something that has to be run before starting spyserver to gain the access to the device?

**Comment by aeroevan** [comment]
It looks like:
```
ENV{ID_SOFTWARE_RADIO}="1"
```
should be sufficient, so:
```
ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", SYMLINK+="airspyhf-%k", ENV{ID_SOFTWARE_RADIO}=1
```
works for me, does that also work in rasbian?

**Comment by darksidelemm** [comment]
Unfortunately not. I set that rule, re-connected the Airspy HF and tried:
- Logging out and logging back in again (via ssh) - could not acquire device
- Running via systemd service - could not acquire device
- 
The AirspyHF could only be accessed using sudo.

I note that in some other cases where that particular udev setting is used... they still have the GROUP setting on the end. e.g. https://github.com/osmocom/rtl-sdr/blob/master/rtl-sdr.rules

**Comment by aeroevan** [comment]
Hmm, it looks like the fedora package patches the group: https://src.fedoraproject.org/rpms/rtl-sdr/blob/rawhide/f/rtl-sdr.spec#_64

and it also looks like it patched the udev rule for airspyone_host: https://src.fedoraproject.org/rpms/airspyone_host/blob/rawhide/f/airspyone_host.spec#_53

but airspyhf wasn't packaged by default. I suppose I could just patch stuff locally and/or get it in upstream fedora packages?

**Comment by darksidelemm** [comment]
I'm not quite sure where you're going here - does this mean you're thinking about reverting the udev rule in this repository back to how it was (and how it is in the airspyone_host repo), and letting the distributions handle the patching to match whatever their internal conventions for udev rules are?

**Comment by aeroevan** [comment]
I'm not an airspy employee, just contributed something that ideally would work across distros but apparently the landscape is more complicated.

I'm honestly surprised that there's apparently no way to associate an ssh session with a logind seat (which would bind the uaccess tagged devices). My devices are mostly accessible via a kvm switch which does associate a console login with a seat which triggers all of the uaccess tagged udev rules

**Comment by darksidelemm** [comment]
Right, so unless there is actually a way to make this work with uaccess, is the best approach just to revert the change you made? 

I note that you didn't suggest or make this change in the airspyone_host repository, which is still using the plugdev approach in its udev rules. I haven't seen any issues from users of non-Debian distributions complaining that the udev rules don't work...  

Have you tried using the rule:
```
ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", SYMLINK+="airspyhf-%k", GROUP="plugdev", MODE="0660", TAG+="uaccess"
```
on Fedora? (Or perhaps with different orderings of GROUP, MODE and TAG?) Does this just break access completely, or just not set the group permissions if the group doesn't exist?

It would be nice if there was a solution that worked everywhere, but I doubt it. It sounds like the best solution here is to ship a udev rule that works for the majority use-case, and include notes in the README for other use-cases.

**Comment by aeroevan** [comment]
anything that references `plugdev` will have to be patched by every non-debian distro (fedora, arch, etc.) but I suppose it's a common enough thing to patch

**Comment by aeroevan** [comment]
Does ubuntu use systemd-sysusers? Rather than relying on a distrospecific plugdev group, how about dynamically creating an airspyhf group that can be used by the udev rules?

That would look like:
```
# cat /etc/sysusers.d/airspyhf.conf 
g airspyhf -

# cat /etc/udev/rules.d/52-airspyhf.rules 
ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", SYMLINK+="airspyhf-%k", ENV{ID_SOFTWARE_RADIO}="1", MODE="0660", GROUP="airspyhf"
```

it might require an explicit `systemd-sysusers` call to create the group and then users would need to be added to the airspyhf group, so maybe not as convenient but should work across distros

**Comment by markjfine** [comment]
I can confirm that plugdev does cause a problem for Fedora 42.

Once I'm done testing something else I found relating to 42, I'll again look into how to make plugdev (or similar) conditional for for just Debian/Raspian users. Otherwise @touil is basically applying something that works for a small user population and potentially breaks for everyone else. As a former s/w developer in this hobby, I can personally tell you he don't need that kind of headache.

**Comment by aeroevan** [comment]
yeah, relying on any specific group will cause an issue. Packaging up the group that's expected to work (i.e. with a sysusers.d entry) should work for any distro that uses systemd, but it will require having users added to the appropriate (`airspyhf` in my example) group

**Comment by markjfine** [comment]
Well, it's worse than that, because if it's built the way it is, and if the cmake option installs the bad rule, the group and mode are stuck unless it's physically reset.

**Comment by markjfine** [comment]
@darksidelemm 
When you run `uname -n` on your Raspian device, what does it return with?
And if you're running Debian, what does it return there, as well?

**Comment by markjfine** [comment]
In an aha-moment, it just occurred to me that the root problems are likely the `MODE` to begin with. `GROUP` is just adding unnecessary ownership problems. Setting `MODE` to 660 gives the user and group read/write, but no execution access, but owner/group is still root/root until you change the group... it may make sense to add world access (e.g., everyone else) to MODE instead of adding a group that just confuses every distro.

The aha-moment was had from looking at what happens in /dev when an Airspy is plugged in in accordance with the specified rule. On Fedora, when you use "uaccess" in TAGS, the rule creates the device as lrwxrwxrwx (or 777) which should be accessible by everybody and their mother-in-law. If Debian/Raspian doesn't create it correctly, just try adding MODE="777" to the rule without specifying a GROUP and I'll bet all the root problems go away.

Incidentally, "666" may also work, but the Pope just died so let's not push our luck, shall we... 😂😇

**Comment by mahtin** [comment]
It would never be `0777` as it's not an executable file/device. That said `0666` isn't correct either. The whole point of the group is being `plugdev` or equivalent with mode `0660` is to make sure joe-random-user doesn't have access to the device.

**Comment by markjfine** [comment]
And yet, that is precisely what uaccess does. It works perfectly across the board for nearly every distro. I'm not @touil, but I think he'd agree that it is quite unreasonable to satisfy the specific requirements of a select few at the risk of making it a lot harder for everyone else.

Personally, I agree this solution isn't the most secure thing in the world, but I don't see how anyone would have access to my Airspy device from the internet unless they were logged in in the first place.

Oh, and yes, execute is not required (even though uaccess sets it), but I guess you also missed the joke.

**Comment by darksidelemm** [comment]
@markjfine  - I'm running a Raspberry Pi 4 with Raspbian Bookworm. It is headless, and only accessed via ssh over network.

uname -a returns: `Linux spyserverX2 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux`

In the specific case I'm talking about, the systemd service is running the airspy spyserver server, which is very often exposed to the internet. That should definitely not be running as a root user. That is different to device-level permissions however.

The issues with uaccess still seem to be users logged in via SSH (e.g - someone setting up and testing a new server), and processes running as a systemd service with user permissions (e.g spyserver). As mentioned in the threads above, using only the uaccess tag, it seems that permissions are not given to users logged in via SSH, or systemd services. 

I'd love to see a solution to get the uaccess approach working in those cases. I'm completely out of my depth with systemd at that point. @aeroevan posted in a closed issue on the systemd github ( https://github.com/systemd/systemd/issues/31227 ) which was talking about kinds of crazy things required to make even just the service case work.

Maybe its worth you spinning up a Raspbian setup and seeing what's going on for yourself?

**Comment by aeroevan** [comment]
Can you give https://github.com/airspy/airspyhf/issues/46#issuecomment-2818398691 a try? to see if creating a systemd-sysusers group and assigning that group access via udev would work?

That way it's still available via group permissions, but the group can be shipped as part of the package (aka it doesn't rely on a plugdev/other magic group existing)

**Comment by darksidelemm** [comment]
At that point, you'd want to do the same kind of thing for the airspyone_host repo too, right? (... and rtlsdr? Same issues there probably). May as well create the plugdev group if it doesn't exist already ;-)
(But yes, perhaps this is a way forward.)
I note that my PR to move back to the group approach was merged. This resolves the issue of the recommended setup approach (which is targeted at Raspberry Pi) on the main airspy website not working, and at least now mentions the potential for issues on other distributions in the Readme.
I'd hazard a guess that users of other distributions probably have more of an idea about the intricacies of udev rules, whereas users running the script on the website are probably linux newbies and wouldn't even know what a user group is, let alone udev.

I'm curious if the issues i've been encountering with accessing the device from a SSH login, or systemd service are present on other distributions (e.g. Fedora) when using the uaccess tag. 
In my case I'm running Raspbian OS Lite, so there's no GUI environments installed at all. I haven't tried using the uaccess rule from a local terminal because, well... I don't have one to hook up.

**Comment by markjfine** [comment]
> uname -a returns: `Linux spyserverX2 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux`

@darksidelemm 
The spyserverX2 is the -n part I was after. If this is installation/distro that everyone is trying to get working, we can use that as part of a conditional define specifically for those systems.

Would appreciate it if others would likewise confirm this so we could start to move forward with an amenable and practicable solution.

@aeroevan 
I agree that using a group that already exists and not inventing something new and potentially problematic is always the way to go. We just need more information from those people above so we can isolate the change to those that need it.

**Comment by darksidelemm** [comment]
Apologies, I ran uname -a instead of uname -n. 
spyserverX2 is the machine's hostname. The distribution is Raspbian ([Raspberry Pi OS](https://www.raspberrypi.com/software/), in my case I'm using the Lite version, which doesnt have any GUI packages), which is Debian based. This is running on a Raspberry Pi 4. 

The [spyserver setup script](http://airspy.com/downloads/install-spyserver-rpi.sh) linked on https://airspy.com/quickstart/ assumes the user is running Raspberry Pi OS on a RPi. It seems to be a very common platform for new users setting up a Spyserver instance.

**Comment by markjfine** [comment]
Also want to point out that as I read back to the beginning, at no point until just today did anyone feel it was important mention that this 'fix' was needed for something to be accessed as a remote radio server via SSH or over a network. You all initially implied the problem was for a single-user system and that the problem was something with your particular Linux distribution.

@darksidelemm 
When you run `uname -a`, the distribution (what is returned from `uname -n`) is usually the second item listed, not the hostname. If I am to use that specific value when creating a conditional rule, I need to know precisely what `uname -n` returns. Otherwise we're just fishing in Jack O'Neill's lake.

**Comment by darksidelemm** [comment]
```
darkside@spyserverX2:~ $ uname -n
spyserverX2
darkside@spyserverX2:~ $ uname -a
Linux spyserverX2 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
```

... and for completeness:
```
darkside@spyserverX2:~ $ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

(Hey, I got the Stargate reference!)

**Comment by markjfine** [comment]
@darksidelemm 
So if you did `uname -s` does it come back as "Debian"? I think that may be the key common thing.
Could feasibly also use ENV{ID}=="debian" if that environment variable is common.

**Comment by aeroevan** [comment]
> [@aeroevan](https://github.com/aeroevan) I agree that using a group that already exists and not inventing something new and potentially problematic is always the way to go. We just need more information from those people above so we can isolate the change to those that need it.

The problem is different distros have different groups, so unless the group name is packaged you can't rely on a group existing in the udev rules

**Comment by markjfine** [comment]
@aeroevan 
So I'm thinking that the process logic is:
1. If we find out this is particular to just Debian and Debian derivative distros (which is kind of sounds like it is, but don't know that for a fact), then we'll need to check the `ID=` line in `/etc/os-release` to see if it says "debian" to determine if any of this is needed in the first place.
2. Then there needs to be a cmake directive added like `-DREMOTE_USER_SYSTEM=ON` for setting this up for non-single-user systems, where GROUP and MODE are needed for security purposes.
3. Depending upon the cmake directive, it would dynamically create 52-airspyhf.rules with a base of `ATTR{idVendor}=="03eb", ATTR{idProduct}=="800c", SYMLINK+="airspyhf-%k"`, whereas `-DREMOTE_USER_SYSTEM=ON` would append `MODE="660", GROUP="airspyhf"`; and the original `-DINSTALL_UDEV_RULES=ON` would just append `TAGS+="uaccess"`.
4. Then there needs to be an optional script as part of the install process that checks to see if group "airspyhf" exists. If it doesn't exist, create it. Once created, loop through all of the local and remote (human) users, ensuring each is added to the group.

That all said, I'm starting to realize (and hope others see) that the scope of this is a lot more than just one simple line in a rules file. It's starting to sound a lot like this should be part of something new called airspyhf_host instead of just a stand-alone airspyhf driver, but that's just me. Maybe that's what [this](https://github.com/airspy/airspyhf/issues/46#issuecomment-2212410129) meant.

**Comment by darksidelemm** [comment]
Seems like a reasonable solution, assuming it's documented well enough. 

I would make it clear in the README that the option is required if you wish to access the Airspy from a systemd service, and that users of distributions without plugdev are probably going to need to create the plugdev group for that to work...
(unless you've found a better solution for that problem yet?)

Has anyone actually confirmed that the uaccess rules work on Debian/Raspbian for a locally logged in user? As mentioned, my RPis are all headless (and most of them are ~50km away), so this is not something I can test easily right now... 

If this PR is merged, @touil  is going to have to change the automated setup script too...  ( http://airspy.com/downloads/install-spyserver-rpi.sh )

**Comment by bigalnz** [comment]
I am happy to give test access to someone on this thread

"Beat it punk!"
- Clint Eastwood

**Comment by markjfine** [comment]
What is likely to be merged is actually not exactly as I described. For one, we discussed making plugdev the default, and uaccess the option. Stay tuned.

If this works well, then I'll look at the next step of automating group creation and the harder part of moving users to it.

I think making the rules file dynamically generated was key to solving this problem and we'll have that soon.

**Comment by aeroevan** [comment]
automating group creation is easy, just dropping a file in sysusers.d and any distro that uses systemd should pick that up

**Comment by markjfine** [comment]
> automating group creation is easy, just dropping a file in sysusers.d and any distro that uses systemd should pick that up

Understand, and that's ok for a default MODE/GROUP installation. I still need to detect if it already exists, but that's trivial.

I'm also (perhaps over-) thinking about what to do when a stand-alone user does a uaccess installation - clearly not install anything into sysusers.d and not even worry about it. That one's also easy.

Where it gets sticky is how to handle the situation where that user mistakenly installs as MODE/GROUP, finds out it doesn't work, but now needs to cleanly revert to uaccess. Do you automatically delete the group or do you interactively ask the user if they want it deleted? I think the latter is safest because they may have needed the group for something else.

I hate putting interactive questions in what's usually a set-and-forget configuration script. Most people don't expect it, might not understand it, or just not read the question and hit return. So the fail safe needs to be a do-nothing result. The question then becomes how does accidentally adding that group affect stand-alone non-Debian or macOS users - also looking at that. I think the answer is 'nothing', but want to make sure.

Frankly, it would bother me if someone's software left behind something I didn't want and/or didn't need (even if I unknowingly did it to myself)... that's what Windows does. lol

**Comment by markjfine** [comment]
PR now also includes automatic plugdev group creation.

**Comment by touil** [comment]
Any tests?

**Comment by markjfine** [comment]
> Any tests?

See notes in PR.

**Comment by markjfine** [comment]
That said, I haven't heard from anyone else on this thread.

**Comment by mahtin** [comment]
Mark,

> That said, I haven't heard from anyone else on this thread.

My apologies, as the instigator of this issue, I'm nowhere near my h/w to test this presently - I'll be able to play with this in a few weeks. That said, I'm very grateful for your work and diligence on this.

**Comment by markjfine** [comment]
While we're at it, incorporated the necessary changes to fix Issue [#55](https://github.com/airspy/airspyhf/issues/55)

**Comment by markjfine** [comment]
Been two months...  Bueller... Bueller... Anyone?

**Comment by touil** [comment]
We should be good with this one.
